[Core.System]
Paths=../../../Engine/Content
Paths=../../../Athena/Content
Paths=../../../Engine/Plugins/Rare/RareShaderTest/Content
Paths=../../../Engine/Plugins/Runtime/Coherent/CoherentUIGTPlugin/Content

[/script/engine.renderersettings]
r.DefaultFeature.LensFlare=False
r.DefaultFeature.MotionBlur=False
r.DefaultFeature.DepthOfField=False
r.DefaultFeature.AmbientOcclusion=False
r.DefaultFeature.AmbientOcclusionStaticFraction=False
r.DefaultFeature.AntiAliasing=0
r.BloomQuality=0
r.MotionBlurQuality=0
r.FastBlurThreshold=0
r.TranslucencyVolumeBlur=0
r.AmbientOcclusionLevels=0
r.AmbientOcclusionRadiusScale=0
r.DepthOfFieldQuality=0
r.MaxAnisotropy=0
r.DistanceFieldAO=0
r.LensFlareQuality=0
r.TonemapperQuality=0
r.SceneColorFormat=3
r.SceneColorFringeQuality=0
r.SSR.Quality=0
r.SSS.Scale=0
r.SSS.SampleSet=0
r.SeparateTranslucency=0
r.Upscale.Quality=0
r.RenderTargetPoolMin=200
r.RefractionQuality=0
r.DetailMode=0
r.OneFrameThreadLag=True
r.EmitterSpawnRateScale=0.5
r.ParticleLODBias=5
r.MaterialQualityLevel=0
r.LightShaftQuality=0
r.TranslucencyLightingVolumeDim=24
r.Streaming.MipBias=3
r.Streaming.PoolSize=400

[SystemSettings]
; ===== ТЕНИ: полное отключение (высший приоритет, перекрывает всё) =====
r.ShadowQuality=0
r.Shadow.CSM.MaxCascades=0
r.Shadow.MaxResolution=2
r.Shadow.RadiusThreshold=1
r.Shadow.DistanceScale=0
r.Shadow.CSM.TransitionScale=0
r.DistanceFieldShadowing=0
r.CapsuleShadows=0
r.ContactShadows=0
r.LightFunctionQuality=0
; ===== ТРАВА / КАМНИ / МУСОР =====
grass.DensityScale=0
foliage.DensityScale=0
foliage.DiscardDataOnLoad=1
grass.DiscardDataOnLoad=1
foliage.LODDistanceScale=0.25
; ===== LOD и дальность прорисовки =====
r.ViewDistanceScale=0.4
r.StaticMeshLODDistanceScale=2
r.SkeletalMeshLODBias=2
; ===== Прочая оптимизация =====
r.HZBOcclusion=0
r.FinishCurrentFrame=0

[/script/engine.engine]
bSmoothFrameRate=False
bDisablePhysXHardwareSupport=True
