; ~ MuXolotl potato optimization - https://github.com/MuXolotl/potato-graphics ~

[/Game/Blueprints/Core/BP_ApplicationSettings.BP_ApplicationSettings_C]
GameLanguage=1
ImmerseHeadsetId=0
AudioOutputFormat=2

[/Script/Athena.AthenaGameUserSettings]
D3DVersionForced=0
MaxVerticalResolution=720
MaxFPS=0
VSync=0
LightingDetail=0
ModelDetail=0
ShadowDetail=0
TextureDetail=0
WaterDetail=0
AnimationQuality=0
MMCThresholdScale=0
ResolutionScaling=60.000000
ParticleEmitterQuality=0
ParticleResolutionQuality=0
BackBufferCount=2
ShowPerformanceCounters=3
SmoothFPS=False
HDR=False
AudioOutputSpatialAudio=False
D3DVersion=11
ParallelRendering=True
GpuCrashDetection=False
DisplayStreamingSoftwareDetectionModal=True
Fullscreen=True
bUseVSync=False
ResolutionSizeX=0
ResolutionSizeY=0
LastUserConfirmedResolutionSizeX=0
LastUserConfirmedResolutionSizeY=0
WindowPosX=-1
WindowPosY=-1
bUseDesktopResolutionForFullscreen=False
FullscreenMode=2
LastConfirmedFullscreenMode=2
Version=5
AudioQualityLevel=0

[ScalabilityGroups]
; Match ResolutionScaling.
sg.ResolutionQuality=60
sg.ViewDistanceQuality=0
sg.AntiAliasingQuality=0
sg.ShadowQuality=0
sg.PostProcessQuality=0
sg.TextureQuality=0
sg.EffectsQuality=0
sg.FoliageQuality=0

; ~ MuXolotl potato optimization - https://github.com/MuXolotl/potato-graphics ~