; ~ MuXolotl potato optimization - https://github.com/MuXolotl/potato-graphics ~

[AntiAliasingQuality@0]
r.MSAA.CompositingSampleCount=0
r.PostProcessAAQuality=0
r.ScreenPercentage=60
r.DefaultFeature.AntiAliasing=0

[ViewDistanceQuality@0]
r.ViewDistanceScale=0.25
r.StaticMeshLODDistanceScale=4
r.SkeletalMeshLODBias=5

[ShadowQuality@0]
; Keep shadow CVars off at sg.ShadowQuality=0.
r.LightFunctionQuality=0
r.ShadowQuality=0
r.Shadow.CSM.MaxCascades=0
r.Shadow.MaxResolution=0
r.Shadow.MaxCSMResolution=0
r.Shadow.RadiusThreshold=0
r.Shadow.DistanceScale=0
r.Shadow.CSM.TransitionScale=0
r.Shadow.SpotLightTransitionScale=0
r.Shadow.TransitionScale=0
r.Shadow.PerObject=0
r.Shadow.Preshadows=0
r.Shadow.NearInstanceShadowOption=0
r.Shadow.MinResolution=0
r.Shadow.MinCSMResolution=0
r.Shadow.CachePreshadow=0
r.Shadow.CachedShadowsCastFromMovablePrimitives=0
r.Shadow.WholeSceneShadowUnbuiltInteractionThreshold=0
r.Shadow.RadiusThresholdRSM=0
r.Shadow.TexelsPerPixel=0
r.Shadow.PreshadowExpand=-1
r.SupportPointLightWholeSceneShadows=0
r.Cache.DrawDirectionalShadowing=0
r.Shadow.PerObjectCastDistanceRadiusScale=0.001
r.MaxCSMRadiusToAllowPerObjectShadows=0.01
r.DistanceFieldShadowing=0
r.HeightFieldShadowing=0
r.AOHeightfieldOcclusion=0
r.HFShadowQuality=0
r.DFShadowScatterTileCulling=0
r.AllowLandscapeShadows=0
r.AllowPointLightCubemapShadows=0
r.AllowSubPrimitiveShadows=0
r.AllowStaticLighting=0
r.CapsuleShadows=0
r.CapsuleDirectShadows=0
r.CapsuleIndirectShadows=0
r.CapsuleMaxDirectOcclusionDistance=0
r.CapsuleMaxIndirectOcclusionDistance=0
r.ContactShadows=0
ShowFlag.DynamicShadows=0
ShowFlag.ShadowsFromEditorHiddenActors=0
ShowFlag.PreviewShadowsIndicator=0
bDrawShadows=0

[PostProcessQuality@0]
; Post-process off.
r.DefaultFeature.Bloom=False
r.DefaultFeature.LensFlare=False
r.DefaultFeature.MotionBlur=False
r.DefaultFeature.DepthOfField=False
r.DefaultFeature.AmbientOcclusion=False
r.DefaultFeature.AutoExposure=False
r.PostProcessAAQuality=0
r.PostProcessing.DisableMaterials=1
r.MotionBlurQuality=0
r.BlurGBuffer=0
r.AmbientOcclusionLevels=0
r.AmbientOcclusionRadiusScale=0
r.AmbientOcclusionMaxQuality=0
r.AmbientOcclusion.FadeRadiusScale=0
r.AOMaxViewDistance=0
r.AOQuality=0
r.GTAO.Quality=0
r.SSGI.Enable=0
r.DepthOfFieldQuality=0
r.RenderTargetPoolMin=200
r.LensFlareQuality=0
r.SceneColorFringeQuality=0
r.BloomQuality=0
r.FastBlurThreshold=0
r.TranslucencyVolumeBlur=0
r.Upscale.Quality=0
r.TonemapperQuality=0
r.Tonemapper.Quality=0
r.Tonemapper.GrainQuantization=0
r.Tonemapper.Sharpen=0
r.EyeAdaptationQuality=0
r.SSR=0
r.SSR.Quality=0
r.ReflectionEnvironment=0
r.LightShaftQuality=0
r.LightShafts=0
ShowFlag.MotionBlur=0
ShowFlag.DepthOfField=0
ShowFlag.LensFlares=0
ShowFlag.PostProcessMaterial=0
ShowFlag.PostProcessing=0
ShowFlag.Tonemapper=0
ShowFlag.Vignette=0
ShowFlag.SSR=0
ShowFlag.ReflectionEnvironment=0

[EffectsQuality@0]
; Particles/fog off.
r.TranslucencyLightingVolumeDim=1
r.TranslucencyLightingVolume=0
r.RefractionQuality=0
r.SSR=0
r.SSR.Quality=0
r.SceneColorFormat=3
r.DetailMode=0
r.MaterialQualityLevel=0
r.ParticleLightQuality=0
r.ParticleLODBias=5
r.EmitterSpawnRateScale=0.0
fx.Niagara.QualityLevel=0
r.Fog=0
r.FogDensity=0
r.VolumetricFog=0
r.Atmosphere=0
r.VolumetricCloud=0
r.SkyAtmosphere=0
ShowFlag.Fog=0
ShowFlag.VolumetricFog=0
ShowFlag.Atmosphere=0

[FoliageQuality@0]
foliage.DensityScale=0
grass.DensityScale=0
foliage.DiscardDataOnLoad=1
grass.DiscardDataOnLoad=1
foliage.LODDistanceScale=0.25

[TextureQuality@0]
r.MipMapLODBias=4
r.Streaming.Boost=0.1
r.Streaming.MipBias=4
r.MaxAnisotropy=0
r.Streaming.PoolSize=128

; ~ MuXolotl potato optimization - https://github.com/MuXolotl/potato-graphics ~